WIDTH = 800
HEIGHT = 600
FPS = 60

# Gameplay
PLAYER_SPEED = 3.2
PLAYER_LIVES = 3
PLAYER_SHOT_COOLDOWN = 18
PLAYER_RESPAWN_INVULNERABILITY = 90

ENEMY_BASE_SPEED = 1.7
ENEMY_SHOT_COOLDOWN = 55

SHELL_SPEED = 7.5

# Backward compatibility with old modules
BULLET_SPEED = SHELL_SPEED
ENEMY_SPEED = ENEMY_BASE_SPEED

